# Generated by Django 2.2.1 on 2019-05-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
    ]
