# Generated by Django 2.2.1 on 2019-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tablegift'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('christening', 'Christening'), ('weeding', 'Weeding'), ('fifteen_party', 'Fifteen Party')], default='weeding', max_length=100, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
