# Generated by Django 2.2.1 on 2019-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20190528_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablegift',
            name='invite',
        ),
        migrations.AddField(
            model_name='tablegift',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tablegift',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
